import { Incident, Ward, User } from "./types";

export const SEED_WARDS: Ward[] = [
  {
    id: 1,
    number: 14,
    name: "Beach Ward (Thekkepuram)",
    zone: "Coastal Central",
    officerName: "K. V. Suresh Kumar",
    officerPhone: "+91 98470 12345",
    slaComplianceRate: 96.8,
    activeIssuesCount: 3,
  },
  {
    id: 2,
    number: 22,
    name: "Mavoor Road Commercial",
    zone: "Transit Hub",
    officerName: "P. R. Anjali Devi",
    officerPhone: "+91 94471 67890",
    slaComplianceRate: 91.2,
    activeIssuesCount: 5,
  },
  {
    id: 3,
    number: 7,
    name: "SM Street Heritage",
    zone: "Downtown Central",
    officerName: "Muhammed Fayaz",
    officerPhone: "+91 98952 34567",
    slaComplianceRate: 98.4,
    activeIssuesCount: 1,
  },
  {
    id: 4,
    number: 12,
    name: "Mananchira Square Ward",
    zone: "Civic Core",
    officerName: "Deepa Nambiar",
    officerPhone: "+91 94963 89012",
    slaComplianceRate: 94.0,
    activeIssuesCount: 2,
  },
  {
    id: 5,
    number: 31,
    name: "Sarovaram Eco-Belt",
    zone: "East Wetlands",
    officerName: "M. Haridasan",
    officerPhone: "+91 98464 56789",
    slaComplianceRate: 89.5,
    activeIssuesCount: 4,
  },
  {
    id: 6,
    number: 45,
    name: "Govt. Medical College Ward",
    zone: "Health Corridor",
    officerName: "Dr. Vinod Varma",
    officerPhone: "+91 94475 23456",
    slaComplianceRate: 95.1,
    activeIssuesCount: 2,
  },
];

export const DEMO_USERS: Record<string, User> = {
  citizen: {
    id: "usr-citizen-01",
    name: "Rohan Nair",
    email: "rohan.nair@civion.org",
    role: "CITIZEN",
    phone: "+91 98950 11223",
    avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=160&q=80",
  },
  officer: {
    id: "usr-officer-14",
    name: "K. V. Suresh Kumar (Ward 14 Officer)",
    email: "suresh.kumar@kozhikodecorp.gov.in",
    role: "OFFICER",
    phone: "+91 98470 12345",
    wardId: 14,
    avatarUrl: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=160&q=80",
  },
  admin: {
    id: "usr-admin-director",
    name: "Rojan Jose (Municipal Administrator)",
    email: "rojan.jose@civion.org",
    role: "ADMIN",
    phone: "+91 98460 99887",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=80",
  },
};

export const SEED_INCIDENTS: Incident[] = [
  {
    id: "civ-inc-001",
    ticketNumber: "CIV-1401",
    title: "Illegal Solid Waste Dumping along South Beach Walkway",
    description: "Multiple plastic sacks and commercial debris dumped near Gandhi statue promenade. Obstructing pedestrian flow and creating bio-hazard.",
    category: "WASTE_DUMPING",
    status: "RESOLVED",
    severity: "HIGH",
    confidenceScore: 0.94,
    latitude: 11.2588,
    longitude: 75.7680,
    address: "South Beach Road, Opp. Marine Aquarium, Kozhikode, Kerala 673032",
    wardNumber: 14,
    // High-res realistic civic photos: waste on urban pavement vs restored clean street
    citizenPhotoUrl: "https://images.unsplash.com/photo-1611288875785-5a50785ffac1?auto=format&fit=crop&w=800&q=80",
    resolutionPhotoUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    isPrivacyRedacted: true,
    originalFileSizeKb: 3420,
    compressedFileSizeKb: 340,
    slaDeadline: new Date(Date.now() - 3600000 * 12).toISOString(),
    isSlaBreached: false,
    resolvedNotes: "Ward 14 Sanitation squad deployed with compactor truck. Site cleared, disinfected with bleaching powder, and security warning sign erected.",
    reporterId: "usr-citizen-01",
    reporterName: "Rohan Nair",
    assignedOfficerId: "usr-officer-14",
    assignedOfficerName: "K. V. Suresh Kumar",
    createdAt: new Date(Date.now() - 3600000 * 28).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    resolvedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: "civ-inc-002",
    ticketNumber: "CIV-2204",
    title: "Severe Asphalt Pothole Cluster outside KSRTC Terminal",
    description: "Deep pothole (approx 28cm deep, 1.2m wide) causing heavy vehicular congestion and acute hazard for two-wheelers during peak hours.",
    category: "POTHOLE",
    status: "IN_PROGRESS",
    severity: "CRITICAL",
    confidenceScore: 0.98,
    latitude: 11.2612,
    longitude: 75.7894,
    address: "Mavoor Road Junction, Near KSRTC Terminal, Kozhikode, Kerala 673004",
    wardNumber: 22,
    citizenPhotoUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
    resolutionPhotoUrl: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=800&q=80",
    isPrivacyRedacted: true,
    originalFileSizeKb: 4100,
    compressedFileSizeKb: 412,
    slaDeadline: new Date(Date.now() + 3600000 * 6).toISOString(),
    isSlaBreached: false,
    reporterId: "usr-citizen-02",
    reporterName: "Aiswarya Menon",
    assignedOfficerId: "usr-officer-22",
    assignedOfficerName: "P. R. Anjali Devi",
    createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "civ-inc-003",
    ticketNumber: "CIV-0708",
    title: "Overhead Heritage Streetlight Malfunction & Dark Corridor",
    description: "Three consecutive heritage lanterns along Mittayi Theruvu pedestrian stretch unlit since thunderstorm, leaving prime shopping zone in darkness.",
    category: "STREETLIGHT",
    status: "DISPATCHED",
    severity: "MEDIUM",
    confidenceScore: 0.89,
    latitude: 11.2514,
    longitude: 75.7818,
    address: "SM Street (Sweet Meat Street), Palayam, Kozhikode, Kerala 673001",
    wardNumber: 7,
    citizenPhotoUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
    resolutionPhotoUrl: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80",
    isPrivacyRedacted: true,
    originalFileSizeKb: 2890,
    compressedFileSizeKb: 295,
    slaDeadline: new Date(Date.now() + 3600000 * 18).toISOString(),
    isSlaBreached: false,
    reporterId: "usr-citizen-03",
    reporterName: "Jithin Thomas",
    assignedOfficerId: "usr-officer-07",
    assignedOfficerName: "Muhammed Fayaz",
    createdAt: new Date(Date.now() - 3600000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: "civ-inc-004",
    ticketNumber: "CIV-1205",
    title: "Main Feeder Pipeline Burst near Mananchira Square Park",
    description: "Treated drinking water gushing under pressure onto sidewalk adjoining the central library gate. Substantial water loss and subsoil erosion.",
    category: "WATER_LEAKAGE",
    status: "ESCALATED_SLA",
    severity: "CRITICAL",
    confidenceScore: 0.96,
    latitude: 11.2541,
    longitude: 75.7788,
    address: "Mananchira West Road, Opp. Public Library, Kozhikode, Kerala 673001",
    wardNumber: 12,
    citizenPhotoUrl: "https://images.unsplash.com/photo-1584467735815-f778f274e296?auto=format&fit=crop&w=800&q=80",
    isPrivacyRedacted: true,
    originalFileSizeKb: 3800,
    compressedFileSizeKb: 380,
    slaDeadline: new Date(Date.now() - 3600000 * 5).toISOString(),
    isSlaBreached: true,
    reporterId: "usr-citizen-04",
    reporterName: "Dr. K. Balakrishnan",
    assignedOfficerId: "usr-officer-12",
    assignedOfficerName: "Deepa Nambiar",
    createdAt: new Date(Date.now() - 3600000 * 29).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: "civ-inc-005",
    ticketNumber: "CIV-3102",
    title: "Storm Drainage Culvert Blocked by Construction Rubble",
    description: "Inflow culvert into Sarovaram wetlands clogged by cement debris. Impending waterlogging threat for adjacent residential colony during high tide.",
    category: "DRAINAGE",
    status: "AI_VERIFIED",
    severity: "HIGH",
    confidenceScore: 0.91,
    latitude: 11.2721,
    longitude: 75.8012,
    address: "Sarovaram Bio Park Entry Rd, Eranjipalam, Kozhikode, Kerala 673006",
    wardNumber: 31,
    citizenPhotoUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80",
    isPrivacyRedacted: true,
    originalFileSizeKb: 3100,
    compressedFileSizeKb: 310,
    slaDeadline: new Date(Date.now() + 3600000 * 24).toISOString(),
    isSlaBreached: false,
    reporterId: "usr-citizen-01",
    reporterName: "Rohan Nair",
    assignedOfficerId: "usr-officer-31",
    assignedOfficerName: "M. Haridasan",
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: "civ-inc-006",
    ticketNumber: "CIV-4509",
    title: "Emergency Ambulance Bay Entrance Road Subsidence",
    description: "Depression and crater forming along the main emergency ramp of Calicut Medical College Hospital. Urgent asphalt stabilization needed.",
    category: "POTHOLE",
    status: "SUBMITTED",
    severity: "CRITICAL",
    confidenceScore: 0.97,
    latitude: 11.2736,
    longitude: 75.8365,
    address: "Medical College Hospital Rd, Chevayur, Kozhikode, Kerala 673008",
    wardNumber: 45,
    citizenPhotoUrl: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80",
    isPrivacyRedacted: true,
    originalFileSizeKb: 3600,
    compressedFileSizeKb: 355,
    slaDeadline: new Date(Date.now() + 3600000 * 8).toISOString(),
    isSlaBreached: false,
    reporterId: "usr-citizen-05",
    reporterName: "Neethu Chandran",
    assignedOfficerId: "usr-officer-45",
    assignedOfficerName: "Dr. Vinod Varma",
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
];
